### ISSUE TITLE
Trying to set application/client volumes

### ISSUE THREAD

**Issue by nyboer** [mk-fg/python-pulse-control#13]
I'm trying to change the volumes of clients with a simple script:
```
from pulsectl import Pulse

with Pulse('ALSA plug-in [python2.7]') as pulse:
  print(pulse.sink_input_list())
  for i,cl in enumerate(pulse.sink_input_list()):
    print('-------------------')
    print(cl.name)
    pulse.sink_input_volume_set(index=cl.index,vol=1000.0)
```
However, I get the error:

```
Traceback (most recent call last):
  File "ctl.py", line 17, in <module>
    pulse.sink_input_volume_set(index=cl.index,vol=1000.0)
  File "/usr/local/lib/python2.7/dist-packages/pulsectl/pulsectl.py", line 531, in _wrapper
    pulse_args = func(*args, **kws) if func else list()
  File "/usr/local/lib/python2.7/dist-packages/pulsectl/pulsectl.py", line 560, in <lambda>
    c.pa.context_set_sink_input_volume, lambda vol: vol.to_struct() )
AttributeError: 'float' object has no attribute 'to_struct'
```
According to the docs, "All volume values in this module are float objects in 0-65536 range", so I'm not clear on what sink_input_volume_set is expecting besides an integer. Any insight?

**Comment by mk-fg** [comment]
It's expecting PulseVolumeInfo object, as in pulseaudio, "volume" is not actually one flat value, but a struct with number of channels and one uint32 value per channel.
In PulseVolumeInfo objects, these uint32 values are normalized to floats, but sink_input_volume_set wrapper still expects full PulseVolumeInfo object, not just float.

Where you can use simple floats however is volume_set_all_chans and volume_change_all_chans methods, i.e.:
```
with Pulse('myclient') as pulse:
  for cl in pulse.sink_input_list():
    pulse.volume_set_all_chans(cl, 1000.0)
```

Though now that you mention it, seem to be a big oversight that it's not listed under that README section that one can/should pass PulseVolumeInfo objects to some methods.

Note that you need to pass full PulseSinkInputInfo object to e.g. volume_set_all_chans because it does:
```
def volume_set_all_chans(self, obj, vol):
  obj.volume.values = [vol for v in obj.volume.values]
  self.volume_set(obj, obj.volume)
```
I.e. changes values in PulseVolumeInfo, and then passes that to actual "set volume" function.

You can tweak values in that PulseVolumeInfo as necessary yourself, and pass it and sink index to sink_input_volume_set.
volume_set above is a wrapper that simply calls appropriate "something_volume_set" func for passed object type.

It's impossible to reconstruct PulseVolumeInfo from a call like `pulse.sink_input_volume_set(index=cl.index,vol=1000.0)` however (without additional `sink_info` call), because number of channels is needed.
So probably best to add a note on which wrappers accept what to the README.

Thanks for pointing it out.

**Comment by mk-fg** [comment]
Hopefully now it's explained a bit better here: https://github.com/mk-fg/python-pulse-control#volume

Let me know if it's still confusing or if there's maybe a better way to address the issue.

**Comment by nyboer** [comment]
You might want to provide a couple examples. That's always handy for hacks like me. 
This worked for me to change the volumes for clients (as listed in the Applications tab of Ubuntu's Sound control panel)
```
from pulsectl import Pulse, PulseVolumeInfo
import time

client='dummy-client'

def allAppVolumes(level):
    with Pulse(client) as pulse:
      # loop through all sink inputs and set the volumes.
      # Weird fact: the sink input won't enumerate unless it is outputing audio
      for i,cl in enumerate(pulse.sink_input_list()):
        print('-------------------')
        print(cl.name,cl.index)
        # pass the volume value as PulseVolumeInfo object
        v = PulseVolumeInfo([level])
        pulse.sink_input_volume_set(index=cl.index,vol=v)

# use a value between 0 and 1
allAppVolumes(0.25)
```

**Comment by mk-fg** [comment]
There are examples for "all chans" stuff right under Usage here: https://github.com/mk-fg/python-pulse-control#usage

I.e.:
```
Simple example:

  from pulsectl import Pulse
  
  with Pulse('volume-increaser') as pulse:
    for sink in pulse.sink_list():
      # Volume is usually in 0-1.0 range, with >1.0 being soft-boosted
      pulse.volume_change_all_chans(sink, 0.1)

...

Misc other tinkering:
...
  >>> sink = pulse.sink_list()[0]
  >>> pulse.volume_change_all_chans(sink, -0.1)
  >>> pulse.volume_set_all_chans(sink, 0.5)
...
```

Though guess it (a) might be not obvious that these also apply to anything, and not just sinks - sources, sink inputs, source outpus - and (b) doesn't really give example for how to work with PulseVolumeInfo's.

Will try to address that, thanks.

**Comment by nyboer** [comment]
Yeah, it's the "working with PulseVolumeInfo" objects that's the mysterious part, and could use a couple examples of what arguments might be fed into PulseVolumeInfo and their purposes.

**Comment by mk-fg** [comment]
Also, a few notes on code snippet above, in no particular order:

- `for i,cl in enumerate(pulse.sink_input_list()):` - enumerate() doesn't seem to be used, and should definitely NOT be used for pulse object indexes or anything like that. Can be just `for cl in pulse.sink_input_list()`.

- `Weird fact: the sink input won't enumerate unless it is outputing audio`

    I think that's because there are simply no sink inputs from app(s) in question unless they actually want to output audio.
    I.e. app can be connected to pulseaudio as a "client", and create any number of sink inputs or source outputs with any properties (e.g. names), and usually don't create these until there is something to input/output and close them right after stream ends.

    Note that there's module-stream-restore in pulseaudio though that remembers and applies volume levels to any such streams, values stored in which you can adjust (or create/delete) using this module.
    If it sounds new/confusing, to see what I mean, `git clone https://github.com/mk-fg/pulseaudio-mixer-cli/`, run pa-mixer-mk3.py from there (should give you curses ui in the terminal), and press "x".

- `v = PulseVolumeInfo([level])`

    This looks kinda bogus, unless you absolutely sure you're using mono audio everywhere.
    I guess pulseaudio auto-maps volume for one channel to however many there is, so it kinda works, but I didn't actually think it'd work at all.

    If you simply want to set volume for all channels, why not do exactly same thing as examples in https://github.com/mk-fg/python-pulse-control#usage show, namely:

        with Pulse('dummy-client') as pulse:
          for cl in pulse.sink_input_list():
            pulse.volume_set_all_chans(cl, 0.25)

    That'd correctly set that value for each channel in `cl.volume`.

    Another way with PulseVolumeInfo from cl.volume:

        with Pulse('dummy-client') as pulse:
          for cl in pulse.sink_input_list():
            cl.volume.value_flat = 0.25
            pulse.volume_set(cl, cl.volume)

    Can also do `PulseVolumeInfo([0.25]*len(cl.volume.values))` or `PulseVolumeInfo(0.25, len(cl.volume.values))` to have PulseVolumeInfo with right number of channels.

    But hey, if the way you did it works fine too - great, shouldn't be any problem there.

- `pulse.sink_input_volume_set(index=cl.index,vol=v)`

    Can just use `pulse.volume_set(cl, v)` as also shown in example above and not bother with whether "cl" is a sink, sink-input, source, source-output or whatever - volume_set wrapper will call the right one for whatever's passed.

    And same as per previous point, `pulse.volume_set_all_chans(0.25)` should probably be easier way to do same thing.

**Comment by mk-fg** [comment]
> Yeah, it's the "working with PulseVolumeInfo" objects that's the mysterious part

Noted, ta.

**Comment by mk-fg** [comment]
Added example with all tricks mentioned above at the end of note on Volume here: https://github.com/mk-fg/python-pulse-control#volume

**Comment by mk-fg** [comment]
Apologies if multiple --amend to README caused the notification-spam from above, keep forgetting that github does rather silly things when you mention its tickets in the commit msgs.
