### ISSUE TITLE
Unloading module raises "IndexError: tuple index out of range"

### ISSUE THREAD

**Issue by Kern3l** [mk-fg/python-pulse-control#20]
I load a module **on callback** like this:

```
pulse.module_load(name=DSP_MODULE_NAME,
                  args=f'sink_name={DSP_SINK_NAME} master={mojo_sink.name} '
                       f'plugin={DSP_PLUGIN_NAME} label={DSP_PLUGIN_NAME}')
```

Results in a loaded module (part of `sink_list()` output):
```
<PulseSinkInfo at 7f8220767a90 - description='LADSPA Plugin ladspa_dsp on Mojo Analog Stereo', index=6, mute=0, name='dsp', channels=2, volumes=[100% 100%]>
```

Works awesome.

Then **on another callback** I want to unload it:
```
pulse.module_unload(name=DSP_MODULE_NAME)
```
(the same global variable `DSP_MODULE_NAME`)

This results in:
```
Traceback (most recent call last):                         
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'                                                 
  File "/usr/local/lib/python3.7/dist-packages/pulsectl/pulsectl.py", line 406, in _pulse_subscribe_cb                 
    try: self.event_callback(PulseEventInfo(ev_t, ev_fac, idx))                                                        
  File "./ssink_renameme.py", line 70, in print_events     
    _setup_mojo()                                          
  File "./ssink_renameme.py", line 88, in _setup_mojo      
    pulse.module_unload(name=DSP_MODULE_NAME)              
  File "/usr/local/lib/python3.7/dist-packages/pulsectl/pulsectl.py", line 549, in _wrapper                            
    else: index, args = args[0], args[1:]                  
IndexError: tuple index out of range
```

I want to replace `pacmd unload-module module-ladspa-sink` with `pulse.module_unload()`. For now I can supplement with running `pacmd` for this case, but this isn't the most elegant solution :)

Thank you for creating this library! :) Especially `event_callback_set` is awesome. My Mojo takes a few seconds to start and I don't have to listen on UDEV and guess how much time I have to sleep before setting up sink for it :)

**Comment by mk-fg** [comment]
Hi,

> pulse.module_unload(name=DSP_MODULE_NAME)

That method wraps libpulse's pa_context_unload_module, which works in the similar way to most things in pulse and operates on "index" value, rather than some matching parameter.
Which kinda makes sense as you can have dozen of modules with same exact name loaded, even with same parameters - e.g. any number of module-null-sink.

To get the index, two options come to mind:
- Use the value returned from module_load, if you want to unload the thing you've loaded in the same app.
- Use module_list, match module there by whatever parameter(s) you want (probably just name will do in this case) and use its "index" attribute.

**Comment by mk-fg** [comment]
> Use the value returned from module_load, if you want to unload the thing you've loaded in the same app.

Here's the example for this particular use-case:
https://github.com/mk-fg/python-pulse-control/blob/7ff0cc1/pulsectl/tests/dummy_instance.py#L274-L280

**Comment by mk-fg** [comment]
> For now I can supplement with running pacmd for this case, but this isn't the most elegant solution :)

Actually, wrt pacmd in particular (which is different from pactl, in that it loads/uses pulse's module-cli, not libpulse calls), there's an option to use same thing from this module via `pulsectl.connect_to_cli()` call.

Simply calling `pulsectl.connect_to_cli()` will return file object wrapping module-cli socket (auto-loading module-cli via SIGUSR2 - same as pacmd does - if necessary), to which you can read/write as if it was "pacmd" console, which uses same syntax/commands/protocol as in e.g. default.pa file.

Here's example of how to use it:
https://github.com/mk-fg/python-pulse-control/blob/7ff0cc1/pulsectl/tests/dummy_instance.py#L218-L225

Run e.g. `python -c 'import pulsectl; help(pulsectl.connect_to_cli)'` to see more details from method description:
https://github.com/mk-fg/python-pulse-control/blob/7ff0cc1302020c3ed6188049a759101758529f98/pulsectl/pulsectl.py#L804-L818

**Comment by mk-fg** [comment]
> Especially event_callback_set is awesome.

Note however that due to how this module wraps libpulse stuff into synchronous calls, instead of e.g. returning twisted/asyncio's futures, there are major limitations on what you can do from these callbacks, but also plenty of ways to work around these, ofc.

README has a bit more info on what I mean here:
https://github.com/mk-fg/python-pulse-control/#event-handling-code-threads

**Comment by mk-fg** [comment]
And lastly, returning to how module_unload works...

It's definitely possible to wrap the thing here to match modules by name (running module_list behind the scenes), so it'd work like unload-module call in module-cli protocol (one you used via pacmd), but it seems like a bad idea, as it'd probably be first thing one'd use, without realizing that it can potentially unload wrong thing or raise errors later (depending on how ambiguity is handled), instantly introducing a bug.

While forcing to use index would make one implement something like `module_index, = filter(lambda m: m.name == module_name, pulse.list_modules())`, where it's more obvious what's happening there and how it can go wrong, as iterator clearly implies cases with 0 or >1 items.

**Comment by Kern3l** [comment]
That's awesome, thank you! I'll check it out the next time I work on it :)
