### ISSUE TITLE
Moving a stream to a different sink

### ISSUE THREAD

**Issue by Hubro** [mk-fg/python-pulse-control#29]
I'm trying to make a script that switches the default sink and moves all playing streams to the default sink.

I found the method `sink_input_move`, but it's completely undocumented. It seems to require 2 integers, but no matter what combination of integers I pass I just get `pulsectl.pulsectl.PulseOperationFailed`. I've tried inputting the indexes of the stream and the sink, the device number and the card number of the sink.

Is this method broken, or am I doing something wrong?

**Comment by mk-fg** [comment]
Quite possibly, as I don't recall ever using it.
Looks like it came from original ctypes code of pulsemixer, and was never tested or touched in any way really.
I'll try to make some dummy test for moving stuff between loopback sinks and see if it works.

**Comment by mk-fg** [comment]
Hm, just tried it, and it seem to work for me in that simple test-case.

Specific code I've used:
https://github.com/mk-fg/python-pulse-control/blob/cc1a761e/pulsectl/tests/dummy_instance.py#L442-L461
It moves simple "paplay /dev/zero" stream between two null-sinks and back, using `pulse.sink_input_move(stream_index, sink_index)` in both cases.

You can try running it on your machine/setup via command like:
`python3 -m unittest pulsectl.tests.all.DummyTests.test_stream_move`
...from the latest git checkout dir.

If it does work for you with null-sinks as well, but does not with some other sink/stream types, one obvious suggestion might be to look at "pulseaudio -v" verbose output, see if it logs some kind of error when that operation fails.

Let me know how it goes, and thanks for reporting it - hopefully test might provide an example to wrt which indexes to use with that method.
(though in general, it's always same stuff as in pulseaudio API method with the same name, so libpulse doxygen docs can be used as a reference)

**Comment by Hubro** [comment]
Thanks, I'll give it another shot and report back as soon as possible.

**Comment by Hubro** [comment]
Well dang, it works now... I swear to god I tested that combination of indexes in the interpreter. Perhaps some indexes changed while I was testing or something. Thanks for the help.
