### ISSUE TITLE
Assertion 'c' failed at ../pulseaudio/src/pulse/context.c

### ISSUE THREAD

**Issue by killown** [mk-fg/python-pulse-control#80]
>>> 
>>> pulse.sink_list()
Assertion 'c' failed at ../pulseaudio/src/pulse/context.c:1238, function pa_context_send_simple_command(). Aborting.
[1]    59361 IOT instruction (core dumped)  python

**Comment by mk-fg** [comment]
Can be misusing the context in some way (e.g. using that on a closed one), so need full code example to try to reproduce it here.
But no idea what it's about otherwise, feel free to reopen with proper "running this code, expected result, actual result, etc" info.
