### ISSUE TITLE
Get default sink

### ISSUE THREAD

**Issue by Core447** [mk-fg/python-pulse-control#81]
I can't find a way to get the active sink/source set by `default_set'. Am I missing something or is it really not available right now?

**Comment by mk-fg** [comment]
Hi.

For some reason these are returned in pulse.server_info() with libpulse, and don't have their own corresponding get-methods.

You can use names from there with get_sink_by_name / get_source_by_name to get sink/source info, e.g.:

``` python
with pulsectl.Pulse() as pulse:
  si = pulse.server_info()
  print([si, pulse.get_sink_by_name(si.default_sink_name)])
```

Not very intuitive though, and maybe indeed worth adding couple methods to get default sink/source from that info specifically.

**Comment by mk-fg** [comment]
Added get methods next to set for sinks/sources in 34c4ba9 / 24.4.0, though if you want both at once, might be more efficient to call server_info() once yourself instead.
Thanks for bringing it up.

**Comment by Core447** [comment]
Ok, perfect, thanks
