### ISSUE TITLE
'sink' events are received with a delay

### ISSUE THREAD

**Issue by shinrax2** [mk-fg/python-pulse-control#85]
im working on a little tool to automate setting application volume based on default sink but im receiving the 'sink' events of changing my default sink delayed
i already tried using 'sink_input' but since those events fire all the time when audio is outputted they are quite unideal for me

any idea how to workaround that?

OS: EndavourOS (arch based rolling release)
Audioserver: Pipewire 1.2.7 with Pipewire-Pulse (providing libpulse API)
pulsectl: 24.11.0

**Comment by mk-fg** [comment]
Code in this module sets that event callback function via libpulse's pa_context_set_subscribe_callback() to run directly, and runs mainloop without any artificial delays, so don't think there should be any significant delay in this module.
So it seems more likely - esp. if you're seeing other events without delays - is that pipewire emits those particular sink events with delay for some reason.
I haven't used pipewire myself yet, so don't know if that might be the case, or about any potential things to look at in its configuration and such.

One solution off the top of my head might be to use some native pipewire API, as presumably pulseaudio one (used by this module) is there just for backwards compatibility, so I'd expect it to be suboptimal in such small ways.
And especially for a new application, I think relying on libpulse API might be a bad idea in general, unless there's no native API option in pipewire.

Either way, don't think this module can do much about it, unfortunately.
